# Generated by Django 5.0.6 on 2024-05-17 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="username",
            field=models.EmailField(
                default="mitchell.dawson@justice.gov.uk",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
            preserve_default=False,
        ),
    ]
