# Generated by Django 5.1.2 on 2024-10-24 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "satisfaction_rating",
                    models.IntegerField(
                        choices=[
                            (5, "Very satisfied"),
                            (4, "Satisfied"),
                            (3, "Neither satisfied or dissatisfied"),
                            (2, "Dissatisfied"),
                            (1, "Very dissatisfied"),
                        ],
                        verbose_name="Satisfaction survey",
                    ),
                ),
                (
                    "how_can_we_improve",
                    models.TextField(
                        blank=True, verbose_name="How can we improve this service?"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("Link is broken", "Broken Link"),
                            ("Owner is incorrect", "Incorrect Owner"),
                            ("Contact is outdated", "Outdated Contact"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="What is wrong with this page?",
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(10)],
                        verbose_name="Can you provide more detail?",
                    ),
                ),
                ("entity_name", models.CharField(max_length=250)),
                ("entity_url", models.CharField(max_length=250)),
                ("data_owner_email", models.CharField(max_length=250)),
                (
                    "user_email",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
            ],
        ),
    ]
