# Generated by Django 5.0.7 on 2024-08-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "satisfaction_rating",
                    models.IntegerField(
                        choices=[
                            (5, "Very satisfied"),
                            (4, "Satisfied"),
                            (3, "Neither satisfied or dissatisfied"),
                            (2, "Dissatisfied"),
                            (1, "Very dissatisfied"),
                        ],
                        verbose_name="Satisfaction survey",
                    ),
                ),
                (
                    "how_can_we_improve",
                    models.TextField(verbose_name="How can we improve this service?"),
                ),
            ],
        ),
    ]
