# Generated by Django 5.1.2 on 2024-10-16 12:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_alter_feedback_how_can_we_improve"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("Broken link", "Broken Link"),
                            ("Incorrect owner", "Incorrect Owner"),
                            ("Outdated contact", "Outdated Contact"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("data_asset_name", models.CharField(max_length=250)),
                ("data_asset_url", models.CharField(max_length=250)),
                (
                    "data_asset_owner_email",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        null=True,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
            ],
        ),
    ]
