# Generated by Django 5.1.3 on 2024-11-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0002_remove_issue_user_email_issue_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="reason",
            field=models.CharField(
                choices=[
                    ("Link is broken", "Broken Link"),
                    ("Data Custodian is incorrect", "Incorrect Custodian"),
                    ("Contact is outdated", "Outdated Contact"),
                    ("Other", "Other"),
                ],
                max_length=50,
                verbose_name="What is wrong with this page?",
            ),
        ),
    ]
