# Generated by Django 5.1.2 on 2024-10-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_reportissue"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportissue",
            name="additional_info",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reportissue",
            name="reason",
            field=models.CharField(
                choices=[
                    ("Broken link", "Broken Link"),
                    ("Incorrect owner", "Incorrect Owner"),
                    ("Outdated contact", "Outdated Contact"),
                    ("Other", "Other"),
                ],
                max_length=50,
                verbose_name="Reason",
            ),
        ),
    ]
