# Generated by Django 5.1.3 on 2024-11-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0003_alter_issue_reason"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="data_owner_email",
            new_name="data_custodian_email",
        ),
        migrations.AlterField(
            model_name="issue",
            name="reason",
            field=models.CharField(
                choices=[
                    ("Link is broken", "Broken Link"),
                    ("Data custodian is incorrect", "Incorrect Custodian"),
                    ("Contact is outdated", "Outdated Contact"),
                    ("Other", "Other"),
                ],
                max_length=50,
                verbose_name="What is wrong with this page?",
            ),
        ),
    ]
