# Generated by Django 5.1.6 on 2025-02-24 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback",
            "0004_rename_data_owner_email_issue_data_custodian_email_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="how_can_we_improve",
            field=models.TextField(
                blank=True, verbose_name="How can we improve this service? (optional)"
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="satisfaction_rating",
            field=models.IntegerField(
                choices=[
                    (5, "Very satisfied"),
                    (4, "Satisfied"),
                    (3, "Neither satisfied or dissatisfied"),
                    (2, "Dissatisfied"),
                    (1, "Very dissatisfied"),
                ],
                verbose_name="How satisfied are you with this service?",
            ),
        ),
    ]
