# Generated by Django 5.2.3 on 2025-09-03 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0005_alter_feedback_how_can_we_improve_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FeedbackYes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("url_path", models.CharField(max_length=250)),
                (
                    "easy_to_find",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="It was easy to find what I needed",
                    ),
                ),
                (
                    "information_useful",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="The information I found was useful",
                    ),
                ),
                (
                    "information_easy_to_understand",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="The information I found was easy to understand",
                    ),
                ),
                (
                    "interested_in_research",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Interested in participating in research to improve the site",
                    ),
                ),
                (
                    "additional_information",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Anything else you would like to tell us? (optional)",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
