# Generated by Django 5.2.3 on 2025-09-04 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_feedbackyes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackyes",
            name="interested_in_research",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                null=True,
                verbose_name="Interested in participating in research to improve the site",
            ),
        ),
        migrations.CreateModel(
            name="FeedBackNo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("url_path", models.CharField(max_length=250)),
                (
                    "additional_information",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Anything else you would like to tell us? (optional)",
                    ),
                ),
                (
                    "interested_in_research",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        null=True,
                        verbose_name="Interested in participating in research to improve the site",
                    ),
                ),
                (
                    "not_clear",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="It was not clear how to find what I needed",
                    ),
                ),
                (
                    "information_not_available",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="The information I needed did not seem to be available",
                    ),
                ),
                (
                    "incomplete_information",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="The information available was incomplete",
                    ),
                ),
                (
                    "difficult_to_understand",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="The information available was difficult to understand",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FeedBackReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("url_path", models.CharField(max_length=250)),
                (
                    "additional_information",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Anything else you would like to tell us? (optional)",
                    ),
                ),
                (
                    "interested_in_research",
                    models.BooleanField(
                        blank=True,
                        choices=[(True, "Yes"), (False, "No")],
                        default=True,
                        null=True,
                        verbose_name="Interested in participating in research to improve the site",
                    ),
                ),
                (
                    "not_working",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="A link isn't working",
                    ),
                ),
                (
                    "needs_fixing",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="A bug needs fixing",
                    ),
                ),
                (
                    "something_else",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        null=True,
                        verbose_name="Something else",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
