# Generated by Django 5.2.3 on 2025-09-05 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback",
            "0007_alter_feedbackyes_interested_in_research_feedbackno_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedbackreport",
            name="interested_in_research",
        ),
    ]
