# Generated by Django 5.1.2 on 2024-10-16 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0007_reportissue_created_reportissue_modified_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportissue",
            name="additional_info",
            field=models.TextField(
                blank=True, verbose_name="Can you provide more detail?"
            ),
        ),
        migrations.AlterField(
            model_name="reportissue",
            name="data_owner_email",
            field=models.CharField(
                max_length=250, validators=[django.core.validators.EmailValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="reportissue",
            name="entity_name",
            field=models.CharField(
                max_length=250,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="reportissue",
            name="entity_url",
            field=models.CharField(
                max_length=250,
                validators=[django.core.validators.MinLengthValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="reportissue",
            name="user_email",
            field=models.CharField(
                blank=True,
                max_length=250,
                validators=[django.core.validators.EmailValidator()],
            ),
        ),
    ]
