# Generated by Django 5.1.2 on 2024-10-18 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0008_alter_reportissue_additional_info_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportissue",
            name="additional_info",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name="Can you provide more detail?",
            ),
        ),
        migrations.AlterField(
            model_name="reportissue",
            name="data_owner_email",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="reportissue",
            name="entity_name",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="reportissue",
            name="entity_url",
            field=models.CharField(max_length=250),
        ),
    ]
