# Generated by Django 5.2.3 on 2025-09-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0008_remove_feedbackreport_interested_in_research"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedbackno",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="feedbackreport",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="feedbackyes",
            name="created_by",
        ),
        migrations.AddField(
            model_name="feedbackno",
            name="created_by_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="feedbackreport",
            name="created_by_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="feedbackyes",
            name="created_by_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
