# Generated by Django 5.1.2 on 2024-10-22 09:23

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0009_alter_reportissue_additional_info_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("Link is broken", "Broken Link"),
                            ("Owner is incorrect", "Incorrect Owner"),
                            ("Contact is outdated", "Outdated Contact"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                        verbose_name="What is wrong with this page?",
                    ),
                ),
                (
                    "additional_info",
                    models.TextField(
                        validators=[django.core.validators.MinLengthValidator(10)],
                        verbose_name="Can you provide more detail?",
                    ),
                ),
                ("entity_name", models.CharField(max_length=250)),
                ("entity_url", models.CharField(max_length=250)),
                ("data_owner_email", models.CharField(max_length=250)),
                (
                    "user_email",
                    models.CharField(
                        blank=True,
                        max_length=250,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ReportIssue",
        ),
    ]
