# Generated by Django 5.2.3 on 2025-09-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0009_remove_feedbackno_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackno",
            name="difficult_to_understand",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="The information available is difficult to understand",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackno",
            name="incomplete_information",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="The information available is incomplete",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackno",
            name="interested_in_research",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                null=True,
                verbose_name="Are you interested in taking part in research on Find MoJ Data",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackyes",
            name="interested_in_research",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                null=True,
                verbose_name="Are you interested in taking part in research on Find MoJ Data",
            ),
        ),
    ]
