# Generated by Django 5.2.3 on 2025-09-05 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0009_remove_feedbackno_created_by_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
