# Generated by Django 5.2.3 on 2025-09-08 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0010_alter_feedbackno_difficult_to_understand_and_more"),
        ("feedback", "0010_delete_feedback"),
    ]

    operations = []
