# Generated by Django 5.1.2 on 2024-10-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0010_issue_delete_reportissue"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
