# Generated by Django 5.2.3 on 2025-09-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0011_merge_20250908_1530"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackno",
            name="additional_information",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Is there anything else you would like to tell us? (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackreport",
            name="additional_information",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Is there anything else you would like to tell us? (optional)",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackyes",
            name="additional_information",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Is there anything else you would like to tell us? (optional)",
            ),
        ),
    ]
