# Generated by Django 5.2.3 on 2025-09-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0012_alter_feedbackno_additional_information_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackno",
            name="interested_in_research",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                null=True,
                verbose_name="Are you interested in taking part in research on Find MoJ Data?",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackyes",
            name="interested_in_research",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                null=True,
                verbose_name="Are you interested in taking part in research on Find MoJ Data?",
            ),
        ),
    ]
