# Generated by Django 5.2.3 on 2025-09-19 14:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0013_alter_feedbackno_interested_in_research_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="issue",
            name="reason",
        ),
        migrations.AlterField(
            model_name="issue",
            name="additional_info",
            field=models.TextField(
                validators=[django.core.validators.MinLengthValidator(10)],
                verbose_name="Please provide as much information as you can to help resolve the issue.",
            ),
        ),
    ]
