# Generated by Django 5.2.7 on 2025-11-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0014_remove_issue_reason_alter_issue_additional_info"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedbackno",
            name="interested_in_research",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                null=True,
                verbose_name="Are you interested in taking part in research on Find MOJ Data?",
            ),
        ),
        migrations.AlterField(
            model_name="feedbackyes",
            name="interested_in_research",
            field=models.BooleanField(
                blank=True,
                choices=[(True, "Yes"), (False, "No")],
                default=True,
                null=True,
                verbose_name="Are you interested in taking part in research on Find MOJ Data?",
            ),
        ),
    ]
