# Generated by Django 5.2.7 on 2026-07-13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0015_alter_feedbackno_interested_in_research_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedbackno",
            name="something_else",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Something else",
            ),
        ),
        migrations.AddField(
            model_name="feedbackno",
            name="what_went_wrong",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Tell us what was wrong",
            ),
        ),
        migrations.AddField(
            model_name="feedbackyes",
            name="something_else",
            field=models.BooleanField(
                blank=True,
                default=False,
                null=True,
                verbose_name="Something else",
            ),
        ),
        migrations.AddField(
            model_name="feedbackyes",
            name="what_went_well",
            field=models.CharField(
                blank=True,
                max_length=250,
                null=True,
                verbose_name="Tell us what went well",
            ),
        ),
    ]
