# Generated by Django 6.0.5 on 2026-07-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0016_feedback_yes_no_something_else_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackreport',
            name='some_other_issue',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Tell us what the issue is'),
        ),
        migrations.AlterField(
            model_name='feedbackno',
            name='interested_in_research',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Are you interested in taking part in research on Find MOJ Data?'),
        ),
        migrations.AlterField(
            model_name='feedbackyes',
            name='interested_in_research',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], null=True, verbose_name='Are you interested in taking part in research on Find MOJ Data?'),
        ),
    ]
