name: 📋 Task
description: Create a Task
title: "📋 <title>"
type: "Task"
body:
  - type: textarea
    id: description
    attributes:
      description: A clear and concise description of the task.
      label: Describe the task.
      value:
    validations:
      required: true
  - type: checkboxes
    id: steps
    attributes:
      description: Steps to address the task.
      label: Steps to Address
    validations:
      required: false
  - type: textarea
    id: complete_when
    attributes:
      description: Task complete when...
      label: Task complete when..
    validations:
      required: false
