# Generated by Django 5.0.6 on 2024-06-10 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Catalogue",
        ),
    ]
