apiVersion: apps/v1
kind: Deployment
metadata:
  name: find-moj-data-deployment
  labels:
    app: find-moj-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: find-moj-data
  template:
    metadata:
      labels:
        app: find-moj-data
    spec:
      containers:
        - name: find-moj-data
          image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: ENV
              value: "${ENV}"
            - name: CATALOGUE_URL
              value: "${CATALOGUE_URL}"
            - name: DEBUG
              value: "${DEBUG}"
            - name: DJANGO_ALLOWED_HOSTS
              value: "${DJANGO_ALLOWED_HOSTS}"
            - name: DJANGO_LOG_LEVEL
              value: "${DJANGO_LOG_LEVEL}"
            - name: SENTRY_DSN
              value: "${SENTRY_DSN}"
            - name: ENABLE_ANALYTICS
              value: "${ENABLE_ANALYTICS}"
            - name: ANALYTICS_ID
              value: "${ANALYTICS_ID}"
            - name: AZURE_AUTH_ENABLED
              value: "${AZURE_AUTH_ENABLED}"
            - name: AZURE_CLIENT_ID
              value: "$AZURE_CLIENT_ID"
            - name: AZURE_REDIRECT_URI
              value: "$AZURE_REDIRECT_URI"
            - name: AZURE_AUTHORITY
              value: "$AZURE_AUTHORITY"      
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: find-moj-data-secrets
                  key: secret-key
            - name: CATALOGUE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: find-moj-data-secrets
                  key: catalogue-token
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: find-moj-data-secrets
                  key: secret-key
            - name: AZURE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: find-moj-data-secrets
                  key: azure-client-secret
