apiVersion: apps/v1
kind: Deployment
metadata:
  name: find-moj-data-deployment
  labels:
    app: find-moj-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: find-moj-data
  template:
    metadata:
      labels:
        app: find-moj-data
    spec:
      containers:
        - name: find-moj-data
          image: ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: CATALOGUE_URL
              value: "${CATALOGUE_URL}"
            - name: DEBUG
              value: "${DEBUG}"
            - name: DJANGO_ALLOWED_HOSTS
              value: "${DJANGO_ALLOWED_HOSTS}"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: find-moj-data-secrets
                  key: secret-key
            - name: CATALOGUE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: find-moj-data-secrets
                  key: catalogue-token
