apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: find-moj-data-ingress
  annotations:
    external-dns.alpha.kubernetes.io/set-identifier: find-moj-data-ingress-${NAMESPACE}-green
    external-dns.alpha.kubernetes.io/aws-weight: "100"
    nginx.ingress.kubernetes.io/whitelist-source-range: 195.59.75.0/24,194.33.192.0/25,194.33.193.0/25,194.33.196.0/25,194.33.197.0/25,51.149.250.0/24,51.149.251.0/24,35.176.93.186/32
spec:
  ingressClassName: default
  tls:
    - hosts:
        - ${NAMESPACE}.apps.live.cloud-platform.service.justice.gov.uk
  rules:
    - host: ${NAMESPACE}.apps.live.cloud-platform.service.justice.gov.uk
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: find-moj-data-service # this should match the metadata.name in service.yml
                port:
                  number: 80
      metrics:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: find-moj-data-service # this should match the metadata.name in service.yml
                port:
                  number: 8080
