apiVersion: v1
kind: Service
metadata:
  name: find-moj-data-service
spec:
  selector:
    app: find-moj-data # this should match the pod label in deployment.yml
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
