name: Deploy (with tests) to dev
# based on https://jacobian.org/til/github-actions-poetry/

on:
  pull_request:
      types: [opened, synchronize, reopened]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    uses: "./.github/workflows/reusable-tests.yml"

  # Deploys to the 'dev' frontend unless pushed to main
  deploy-to-dev:
    needs: [tests]
    uses: "./.github/workflows/reusable-build-and-deploy.yml"
    with:
      env: "dev"
    secrets:
      kube_namespace: ${{ secrets.KUBE_NAMESPACE }}
      kube_cert: ${{ secrets.KUBE_CERT }}
      kube_cluster: ${{ secrets.KUBE_CLUSTER }}
      kube_token: ${{ secrets.KUBE_TOKEN }}
      ecr_role_to_assume: ${{ secrets.DEV_ECR_ROLE_TO_ASSUME }}
      secret_key: ${{ secrets.SECRET_KEY }}
      catalogue_token: ${{ secrets.CATALOGUE_TOKEN }}
      slack_alert_webhook: ${{ secrets.SLACK_ALERT_WEBHOOK }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
