name: deploy

on:
  push:
    branches: [main]

jobs:
  test:
    uses: "./.github/workflows/deploy-generic.yml"
    with:
      env: "test"
      ecr_repository: "${{ vars.TEST_ECR_REPOSITORY }}"
      ecr_region: "${{ vars.TEST_ECR_REGION }}"
      debug: "${{ vars.DEBUG }}"
      django_allowed_hosts: "${{ vars.DJANGO_ALLOWED_HOSTS }}"
      catalogue_url: "${{ vars.CATALOGUE_URL }}"
    secrets:
      kube_namespace: "${{ secrets.KUBE_NAMESPACE }}"
      kube_cert: "${{ secrets.KUBE_CERT }}"
      kube_cluster: "${{ secrets.KUBE_CLUSTER }}"
      kube_token: "${{ secrets.KUBE_TOKEN }}"
      ecr_role_to_assume: "${{ secrets.TEST_ECR_ROLE_TO_ASSUME }}"
      secret_key: "${{ secrets.SECRET_KEY }}"
      catalogue_token: "${{ secrets.CATALOGUE_TOKEN }}"

  dev:
    uses: "./.github/workflows/deploy-generic.yml"
    needs: test
    with:
      env: "dev"
      ecr_repository: "${{ vars.TEST_ECR_REPOSITORY }}"
      ecr_region: "${{ vars.TEST_ECR_REGION }}"
      debug: "${{ vars.DEBUG }}"
      django_allowed_hosts: "${{ vars.DJANGO_ALLOWED_HOSTS }}"
      catalogue_url: "${{ vars.CATALOGUE_URL }}"
    secrets:
      kube_namespace: "${{ secrets.KUBE_NAMESPACE }}"
      kube_cert: "${{ secrets.KUBE_CERT }}"
      kube_cluster: "${{ secrets.KUBE_CLUSTER }}"
      kube_token: "${{ secrets.KUBE_TOKEN }}"
      ecr_role_to_assume: "${{ secrets.TEST_ECR_ROLE_TO_ASSUME }}"
      secret_key: "${{ secrets.SECRET_KEY }}"
      catalogue_token: "${{ secrets.CATALOGUE_TOKEN }}"

  preprod:
    uses: "./.github/workflows/deploy-generic.yml"
    needs: dev
    with:
      env: "preprod"
      ecr_repository: ${{ vars.TEST_ECR_REPOSITORY }}
      ecr_region: ${{ vars.TEST_ECR_REGION }}
      debug: ${{ vars.DEBUG }}
      django_allowed_hosts: ${{ vars.DJANGO_ALLOWED_HOSTS }}
      catalogue_url: ${{ vars.CATALOGUE_URL }}
    secrets:
      kube_namespace: ${{ secrets.KUBE_NAMESPACE }}
      kube_cert: ${{ secrets.KUBE_CERT }}
      kube_cluster: ${{ secrets.KUBE_CLUSTER }}
      kube_token: ${{ secrets.KUBE_TOKEN }}
      ecr_role_to_assume: ${{ secrets.TEST_ECR_ROLE_TO_ASSUME }}
      secret_key: ${{ secrets.SECRET_KEY }}
      catalogue_token: ${{ secrets.CATALOGUE_TOKEN }}
