name: deploy

on:
  push:
    branches: [main]

jobs:
  dev:
    uses: "./.github/workflows/deploy-generic.yml"
    with:
      env: "dev"
    secrets:
      kube_namespace: ${{ secrets.KUBE_NAMESPACE }}
      kube_cert: ${{ secrets.KUBE_CERT }}
      kube_cluster: ${{ secrets.KUBE_CLUSTER }}
      kube_token: ${{ secrets.KUBE_TOKEN }}
      ecr_role_to_assume: ${{ secrets.DEV_ECR_ROLE_TO_ASSUME }}
      secret_key: ${{ secrets.SECRET_KEY }}
      catalogue_token: ${{ secrets.CATALOGUE_TOKEN }}
      slack_alert_webhook: ${{ secrets.SLACK_ALERT_WEBHOOK }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}

  test:
    uses: "./.github/workflows/deploy-generic.yml"
    needs: dev
    with:
      env: "test"
    secrets:
      kube_namespace: ${{ secrets.KUBE_NAMESPACE }}
      kube_cert: ${{ secrets.KUBE_CERT }}
      kube_cluster: ${{ secrets.KUBE_CLUSTER }}
      kube_token: ${{ secrets.KUBE_TOKEN }}
      ecr_role_to_assume: ${{ secrets.TEST_ECR_ROLE_TO_ASSUME }}
      secret_key: ${{ secrets.SECRET_KEY }}
      catalogue_token: ${{ secrets.CATALOGUE_TOKEN }}
      slack_alert_webhook: ${{ secrets.SLACK_ALERT_WEBHOOK }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}

  preprod:
    uses: "./.github/workflows/deploy-generic.yml"
    needs: test
    with:
      env: "preprod"
    secrets:
      kube_namespace: ${{ secrets.KUBE_NAMESPACE }}
      kube_cert: ${{ secrets.KUBE_CERT }}
      kube_cluster: ${{ secrets.KUBE_CLUSTER }}
      kube_token: ${{ secrets.KUBE_TOKEN }}
      ecr_role_to_assume: ${{ secrets.PREPROD_ECR_ROLE_TO_ASSUME }}
      secret_key: ${{ secrets.SECRET_KEY }}
      catalogue_token: ${{ secrets.CATALOGUE_TOKEN }}
      slack_alert_webhook: ${{ secrets.SLACK_ALERT_WEBHOOK }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}

  prod:
    uses: "./.github/workflows/deploy-generic.yml"
    needs: preprod
    with:
      env: "prod"
    secrets:
      kube_namespace: ${{ secrets.KUBE_NAMESPACE }}
      kube_cert: ${{ secrets.KUBE_CERT }}
      kube_cluster: ${{ secrets.KUBE_CLUSTER }}
      kube_token: ${{ secrets.KUBE_TOKEN }}
      ecr_role_to_assume: ${{ secrets.PROD_ECR_ROLE_TO_ASSUME }}
      secret_key: ${{ secrets.SECRET_KEY }}
      catalogue_token: ${{ secrets.CATALOGUE_TOKEN }}
      slack_alert_webhook: ${{ secrets.SLACK_ALERT_WEBHOOK }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
