name: Deploy to Prod on Published Release

on:
  release:
    types: [published]

jobs:
  code-tests:
    uses: "./.github/workflows/reusable-tests.yml"

  release-datahub-client:
    needs: code-tests
    if: ${{ needs.code-tests.outputs.datahub-client-path == 'true' }}
    uses: "./.github/workflows/reusable-publish-datahub-client.yml"

  build:
    needs: code-tests
    uses: "./.github/workflows/reusable-build.yml"
    secrets:
      slack_alert_webhook: ${{ secrets.SLACK_ALERT_WEBHOOK }}

  deploy-prod:
    uses: "./.github/workflows/reusable-push-and-deploy.yml"
    needs: build
    with:
      env: "prod"
    secrets:
      kube_namespace: ${{ secrets.KUBE_NAMESPACE }}
      kube_cert: ${{ secrets.KUBE_CERT }}
      kube_cluster: ${{ secrets.KUBE_CLUSTER }}
      kube_token: ${{ secrets.KUBE_TOKEN }}
      ecr_role_to_assume: ${{ secrets.PROD_ECR_ROLE_TO_ASSUME }}
      secret_key: ${{ secrets.SECRET_KEY }}
      catalogue_token: ${{ secrets.CATALOGUE_TOKEN }}
      slack_alert_webhook: ${{ secrets.SLACK_ALERT_WEBHOOK }}
      azure_client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
