name: runbooks broken link check
on:
    schedule:
        # Once per day at 00:00
        - cron: "0 0 * * *"

jobs:
    runbooks-broken-link-check:
        runs-on: ubuntu-latest
        permissions:
            issues: write
        steps:
            - uses: actions/checkout@v4

            - name: Link Checker
              id: Lychee
              uses: lycheeverse/lychee-action@v2
              with:
                args: --verbose --format detailed https://runbooks.find-moj-data.service.justice.gov.uk/
                fail: false


            # Uncomment the following block to create an issue if there are broken links
            # - name: Create Issue From File
            #   if: steps.Lychee.outputs.exit_code != 0
            #   uses: peter-evans/create-issue-from-file@v5
            #   with:
            #       title: Link Checker Report
            #       content-filepath: ./lychee/out.md
            #       labels: report, automated issue
